#!/usr/bin/env python3
"""
ARAM voice render — self-contained. Generated by scripts/render_tts.py --emit-colab.
Do not edit by hand; regenerate when the spoken strings or the manifest change.

Every line ARAM says is embedded below, so this file needs no checkout of the repo. In
Google Colab:

    1. Runtime > Change runtime type > T4 GPU
    2. Upload this file (folder icon in the left sidebar), then run these in a cell:

       !pip install -q git+https://github.com/huggingface/parler-tts.git soundfile numpy
       from huggingface_hub import notebook_login; notebook_login()
       !python aram_colab_render.py

    3. Download aram-audio.zip and unzip it into public/audio/ in the repo.

The model is gated: accept the terms at huggingface.co/ai4bharat/indic-parler-tts first.
"""

import shutil
import subprocess
import sys
from pathlib import Path

MODEL_ID = "ai4bharat/indic-parler-tts"
MP3_BITRATE = "48k"
SEED = 7
OUT = Path("audio")

# Conditions raw model output so clips can play back to back: matches loudness across
# languages, and stops each clip beginning or ending on a discontinuity.
AUDIO_FILTER = (
    "loudnorm=I=-16:TP=-1.5:LRA=11,aresample=24000,afade=t=in:st=0:d=0.04,areverse,afade=t=in:st=0:d=0.06,areverse,adelay=60:all=1,apad=pad_dur=0.12"
)

# Reused verbatim for every clip in a language: all of these lines must sound like one
# person. If a voice drifts or sounds wrong, change the speaker name here to one the model
# card recommends for that language and re-run.
DESCRIPTIONS = {
    "en": "Mary speaks in a warm, gentle, reassuring voice at a slow and unhurried pace. The recording is very clear and close-sounding, with no background noise.",
    "ta": "Jaya speaks in a warm, gentle, reassuring voice at a slow and unhurried pace. The recording is very clear and close-sounding, with no background noise."
}

TEXTS = {
    "en": {
        "s04.title": "A note for your parent or guardian",
        "s04.does1": "Helps your child talk about how they feel",
        "s04.does2": "Provides structured wellbeing check-ins",
        "s04.does3": "Connects to helplines if there is a safety concern",
        "s04.privacy1": "We do not share your child's responses with teachers",
        "s04.privacy2": "Only minimal data shared with helplines in emergencies",
        "s04.privacy3": "Your child's sessions are private",
        "s04.consentNote": "By tapping 'I give my consent' you confirm you are a parent or guardian and agree to ARAM supporting this child.",
        "s05.titleSpoken": "Can I support you from here?",
        "s05.warm": "I'm here to help you feel a little calmer, a little clearer, and not alone with what you're feeling.",
        "s05.question": "Is it okay if I stay with you and support you in the ways I can?",
        "s11.title": "Just checking in on something",
        "s11.warm": "Last time we spoke, things felt a bit heavy. I wanted to ask — would you like to talk to a real person about what you've been going through?",
        "emergency.title": "You're not alone right now",
        "emergency.subtitle": "If you're in danger or thinking of hurting yourself, please reach out. Talking to someone helps.",
        "emergency.reassure": "Reaching out is a brave and strong thing to do. These services are free and confidential.",
        "greeting.morning": "Good morning",
        "greeting.afternoon": "Good afternoon",
        "greeting.evening": "Good evening",
        "greeting.night": "Good night",
        "s10.proud": "We're proud of your progress!",
        "s10.todayLabel": "What would you like to do today?",
        "s01.welcome": "Welcome to your safe space.",
        "s01.listen": "I'm here to listen, support, and help you feel better.",
        "s01.brave": "You've just taken a brave step by being here. Whether you're feeling stressed, worried, sad, or just need someone to talk to — I'm here for you.",
        "s09.enterPin": "Enter your PIN",
        "s09.lockedSub": "For your safety this space is locked. Please contact your school coordinator to unlock it.",
        "s02.intro1": "This space is just for you.",
        "s02.intro2": "Let's set it up.",
        "s02.chooseLanguage": "Choose your language",
        "s02.schoolCodeSpoken": "Then enter your school code.",
        "s03.title": "What shall I call you?",
        "s03.subtitle": "You can use a nickname or any name you like.",
        "s03.fieldsSpoken": "Please enter your nickname, your date of birth, and create a four-digit PIN.",
        "s06.title": "Can we use your camera?",
        "s06.subtitle": "This is completely optional",
        "s06.note": "If you say no, ARAM still works fully. Camera is never used without your permission.",
        "s07.title": "Can we listen to your voice?",
        "s07.subtitle": "Also completely optional",
        "s07.note": "Voice is separate from camera. You can allow one without the other.",
        "s08.titleSpoken": "You're all set!",
        "s08.readyNote": "ARAM is ready. Let's start by picking what you'd like to talk about today."
    },
    "ta": {
        "s04.title": "உங்கள் பெற்றோர் அல்லது பாதுகாவலருக்கு ஒரு குறிப்பு",
        "s04.does1": "உங்கள் குழந்தை தங்கள் உணர்வுகளைப் பற்றிப் பேச உதவுகிறது",
        "s04.does2": "கட்டமைக்கப்பட்ட நல்வாழ்வு சரிபார்ப்புகளை வழங்குகிறது",
        "s04.does3": "பாதுகாப்பு கவலை இருந்தால் உதவி எண்களுடன் இணைக்கிறது",
        "s04.privacy1": "உங்கள் குழந்தையின் பதில்களை ஆசிரியர்களுடன் பகிர்வதில்லை",
        "s04.privacy2": "அவசரநிலைகளில் மட்டுமே குறைந்தபட்ச தரவு உதவி எண்களுடன் பகிரப்படும்",
        "s04.privacy3": "உங்கள் குழந்தையின் அமர்வுகள் தனிப்பட்டவை",
        "s04.consentNote": "'நான் என் ஒப்புதலை அளிக்கிறேன்' என்பதைத் தட்டுவதன் மூலம், நீங்கள் பெற்றோர் அல்லது பாதுகாவலர் என்பதை உறுதிப்படுத்தி, இந்தக் குழந்தையை ARAM ஆதரிப்பதை ஏற்கிறீர்கள்.",
        "s05.titleSpoken": "இங்கிருந்து நான் உங்களை ஆதரிக்கலாமா?",
        "s05.warm": "நீங்கள் சற்று அமைதியாகவும், சற்று தெளிவாகவும், உங்கள் உணர்வுகளுடன் தனியாக இல்லாமலும் உணர உதவ இங்கே இருக்கிறேன்.",
        "s05.question": "நான் உங்களுடன் இருந்து, என்னால் முடிந்த வழிகளில் உங்களை ஆதரிப்பது சரியா?",
        "s11.title": "ஒரு விஷயத்தைப் பற்றி விசாரிக்கிறேன்",
        "s11.warm": "கடந்த முறை நாம் பேசியபோது, விஷயங்கள் சற்று கனமாக இருந்தன. நீங்கள் அனுபவித்தவற்றைப் பற்றி உண்மையான ஒருவரிடம் பேச விரும்புகிறீர்களா என்று கேட்க விரும்பினேன்.",
        "emergency.title": "இந்த நேரத்தில் நீங்கள் தனியாக இல்லை",
        "emergency.subtitle": "நீங்கள் ஆபத்தில் இருந்தால் அல்லது உங்களைத் தானே காயப்படுத்திக்கொள்ள நினைத்தால், தயவுசெய்து தொடர்பு கொள்ளுங்கள். யாரிடமாவது பேசுவது உதவும்.",
        "emergency.reassure": "தொடர்பு கொள்வது ஒரு தைரியமான, வலிமையான செயல். இந்த சேவைகள் இலவசம் மற்றும் ரகசியமானவை.",
        "greeting.morning": "காலை வணக்கம்",
        "greeting.afternoon": "மதிய வணக்கம்",
        "greeting.evening": "மாலை வணக்கம்",
        "greeting.night": "இனிய இரவு",
        "s10.proud": "உங்கள் முன்னேற்றத்தில் நாங்கள் பெருமிதம் கொள்கிறோம்!",
        "s10.todayLabel": "இன்று நீங்கள் என்ன செய்ய விரும்புகிறீர்கள்?",
        "s01.welcome": "உங்கள் பாதுகாப்பான இடத்திற்கு வரவேற்கிறோம்.",
        "s01.listen": "நான் உங்களைக் கேட்கவும், ஆதரிக்கவும், நன்றாக உணர உதவவும் இங்கே இருக்கிறேன்.",
        "s01.brave": "இங்கே வந்ததன் மூலம் நீங்கள் ஒரு தைரியமான அடியை எடுத்துவைத்துள்ளீர்கள். மன அழுத்தம், கவலை, வருத்தம், அல்லது யாரிடமாவது பேச வேண்டும் என்றாலும் — நான் உங்களுக்காக இங்கே இருக்கிறேன்.",
        "s09.enterPin": "உங்கள் PIN ஐ உள்ளிடவும்",
        "s09.lockedSub": "உங்கள் பாதுகாப்பிற்காக இந்த இடம் பூட்டப்பட்டுள்ளது. திறக்க உங்கள் பள்ளி ஒருங்கிணைப்பாளரைத் தொடர்பு கொள்ளவும்.",
        "s02.intro1": "இந்த இடம் உங்களுக்காக மட்டுமே.",
        "s02.intro2": "அதை அமைப்போம்.",
        "s02.chooseLanguage": "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
        "s02.schoolCodeSpoken": "பிறகு உங்கள் பள்ளி குறியீட்டை உள்ளிடவும்.",
        "s03.title": "உங்களை என்ன அழைக்கட்டும்?",
        "s03.subtitle": "செல்லப்பெயர் அல்லது நீங்கள் விரும்பும் எந்தப் பெயரையும் பயன்படுத்தலாம்.",
        "s03.fieldsSpoken": "உங்கள் செல்லப்பெயர், பிறந்த தேதி மற்றும் நான்கு இலக்க ரகசிய எண்ணை உள்ளிடவும்.",
        "s06.title": "உங்கள் கேமராவைப் பயன்படுத்தலாமா?",
        "s06.subtitle": "இது முற்றிலும் விருப்பமானது",
        "s06.note": "நீங்கள் வேண்டாம் என்றால், ARAM முழுமையாக இயங்கும். உங்கள் அனுமதியின்றி கேமரா ஒருபோதும் பயன்படுத்தப்படாது.",
        "s07.title": "உங்கள் குரலைக் கேட்கலாமா?",
        "s07.subtitle": "இதுவும் முற்றிலும் விருப்பமானது",
        "s07.note": "குரல் கேமராவிலிருந்து தனியானது. ஒன்றை மற்றொன்று இல்லாமல் அனுமதிக்கலாம்.",
        "s08.titleSpoken": "நீங்கள் தயார்!",
        "s08.readyNote": "ARAM தயார். இன்று நீங்கள் எதைப் பற்றிப் பேச விரும்புகிறீர்கள் என்பதைத் தேர்ந்தெடுப்பதன் மூலம் தொடங்குவோம்."
    }
}


def main() -> None:
    import soundfile as sf
    import torch
    from parler_tts import ParlerTTSForConditionalGeneration
    from transformers import AutoTokenizer

    if not shutil.which("ffmpeg"):
        sys.exit("error: ffmpeg not found")

    device = "cuda:0" if torch.cuda.is_available() else "cpu"
    if device == "cpu":
        print("device: CPU — no GPU found. Expect hours, not minutes.")
        print("Colab: Runtime > Change runtime type > T4 GPU, then rerun.")
    else:
        print(f"device: {device} ({torch.cuda.get_device_name(0)})")

    print(f"loading {MODEL_ID} …")
    model = ParlerTTSForConditionalGeneration.from_pretrained(MODEL_ID).to(device)
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    desc_tokenizer = AutoTokenizer.from_pretrained(model.config.text_encoder._name_or_path)
    rate = model.config.sampling_rate

    for lang, entries in TEXTS.items():
        out_dir = OUT / lang
        out_dir.mkdir(parents=True, exist_ok=True)
        tmp = out_dir / "_tmp.wav"
        desc = DESCRIPTIONS[lang]
        print(f"\n[{lang}] voice: {desc}")

        desc_ids = desc_tokenizer(desc, return_tensors="pt").to(device)
        for i, (key, text) in enumerate(entries.items(), 1):
            mp3 = out_dir / f"{key}.mp3"
            if mp3.exists():
                print(f"[{lang}] {i}/{len(entries)} {key} — exists, skipping")
                continue
            print(f"[{lang}] {i}/{len(entries)} {key}: {text[:60]}…")
            # Per-clip seed: one bad line can be deleted and re-rendered without
            # disturbing the others that were already listened to and approved.
            torch.manual_seed(SEED)
            prompt_ids = tokenizer(text, return_tensors="pt").to(device)
            generation = model.generate(
                input_ids=desc_ids.input_ids,
                attention_mask=desc_ids.attention_mask,
                prompt_input_ids=prompt_ids.input_ids,
                prompt_attention_mask=prompt_ids.attention_mask,
            )
            sf.write(tmp, generation.cpu().numpy().squeeze(), samplerate=rate)
            subprocess.run(
                ["ffmpeg", "-y", "-loglevel", "error", "-i", str(tmp), "-af", AUDIO_FILTER,
                 "-codec:a", "libmp3lame", "-b:a", MP3_BITRATE, "-ac", "1",
                 "-ar", str(rate), str(mp3)],
                check=True,
            )
        tmp.unlink(missing_ok=True)

    shutil.make_archive("aram-audio", "zip", OUT)
    clips = list(OUT.rglob("*.mp3"))
    size = sum(f.stat().st_size for f in clips) / 1_048_576
    print(f"\ndone — {len(clips)} clips, {size:.2f} MB -> aram-audio.zip")
    print("Unzip into public/audio/ so you get public/audio/en/*.mp3 and .../ta/*.mp3")


if __name__ == "__main__":
    main()
