#!/usr/bin/env python3
"""
ARAM voice render — self-contained. Generated by scripts/render_tts.py --emit-colab.
Do not edit by hand; regenerate when the spoken strings or the manifest change.

Every line ARAM says is embedded below, so this file needs no checkout of the repo. In
Google Colab:

    1. Runtime > Change runtime type > T4 GPU
    2. Upload this file (folder icon in the left sidebar), then run these in a cell:

       !pip install -q git+https://github.com/huggingface/parler-tts.git soundfile numpy
       from huggingface_hub import notebook_login; notebook_login()
       !python aram_colab_render.py

    3. Download aram-audio.zip and unzip it into public/audio/ in the repo.

The model is gated: accept the terms at huggingface.co/ai4bharat/indic-parler-tts first.
"""

import shutil
import subprocess
import sys
from pathlib import Path

MODEL_ID = "ai4bharat/indic-parler-tts"
MP3_BITRATE = "48k"
SEED = 7
OUT = Path("audio")

# Conditions raw model output so clips can play back to back: matches loudness across
# languages, and stops each clip beginning or ending on a discontinuity.
AUDIO_FILTER = (
    "loudnorm=I=-16:TP=-1.5:LRA=11,aresample=24000,afade=t=in:st=0:d=0.04,areverse,afade=t=in:st=0:d=0.06,areverse,adelay=60:all=1,apad=pad_dur=0.12"
)

# Reused verbatim for every clip in a language: all of these lines must sound like one
# person. If a voice drifts or sounds wrong, change the speaker name here to one the model
# card recommends for that language and re-run.
DESCRIPTIONS = {
    "en": "Mary speaks in a warm, gentle, reassuring voice at a slow and unhurried pace. The recording is very clear and close-sounding, with no background noise.",
    "hi": "Divya speaks in a warm, gentle, reassuring voice at a slow and unhurried pace. The recording is very clear and close-sounding, with no background noise.",
    "ta": "Jaya speaks in a warm, gentle, reassuring voice at a slow and unhurried pace. The recording is very clear and close-sounding, with no background noise.",
    "te": "Lalitha speaks in a warm, gentle, reassuring voice at a slow and unhurried pace. The recording is very clear and close-sounding, with no background noise.",
    "ml": "Anjali speaks in a warm, gentle, reassuring voice at a slow and unhurried pace. The recording is very clear and close-sounding, with no background noise."
}

TEXTS = {
    "en": {
        "s04.title": "A note for your parent or guardian",
        "s04.subtitle": "Please hand the phone to a trusted adult",
        "s04.doesTitle": "What ARAM does",
        "s04.does1": "Helps your child talk about how they feel",
        "s04.does2": "Provides structured wellbeing check-ins",
        "s04.does3": "Connects to helplines if there is a safety concern",
        "s04.privacyTitle": "Privacy promise",
        "s04.privacy1": "We do not share your child's responses with teachers",
        "s04.privacy2": "Only minimal data shared with helplines in emergencies",
        "s04.privacy3": "Your child's sessions are private",
        "s04.consentNote": "By tapping 'I give my consent' you confirm you are a parent or guardian and agree to ARAM supporting this child.",
        "s05.titleSpoken": "Can I support you from here?",
        "s05.canTitle": "I can:",
        "s05.can1": "Help you notice and calm difficult feelings",
        "s05.can2": "Suggest small steps that may make things lighter",
        "s05.can3": "Help you reach a real helper if I'm very worried about your safety",
        "s05.cannotTitle": "I cannot:",
        "s05.cannot1": "Replace a doctor, teacher, or counsellor",
        "s05.cannot2": "Make decisions for you",
        "s05.cannot3": "Share your details without your permission, except for your safety",
        "s05.warm": "I'm here to help you feel a little calmer, a little clearer, and not alone with what you're feeling.",
        "s05b.title": "Let's register your face",
        "s05b.subtitle": "So you can log back in with a PIN or your face",
        "s05b.captureCtaSpoken": "Please register — tap to turn on your camera.",
        "s11.title": "Just checking in on something",
        "s11.warm": "Last time we spoke, things felt a bit heavy. I wanted to ask — would you like to talk to a real person about what you've been going through?",
        "s11.note": "Whatever you choose is completely okay. This is your space.",
        "emergency.title": "You're not alone right now",
        "emergency.subtitle": "If you're in danger or thinking of hurting yourself, please reach out. Talking to someone helps.",
        "emergency.reassure": "Reaching out is a brave and strong thing to do. These services are free and confidential.",
        "greeting.morning": "Good morning",
        "greeting.afternoon": "Good afternoon",
        "greeting.evening": "Good evening",
        "greeting.night": "Good night",
        "s10.welcomeBackSpoken": "Welcome back!",
        "s10.proud": "We're proud of your progress!",
        "s10.todayLabel": "What would you like to do today?",
        "s01.welcomeSpoken": "Welcome to your safe space. I'm here to listen, support, and help you feel better. Let's Begin Your Journey.",
        "s09.enterPinSpoken": "Welcome back! Enter your PIN, or log in with your registered face.",
        "s09.lockedSub": "For your safety this space is locked. Please contact your school coordinator to unlock it.",
        "s02.intro1": "This space is just for you.",
        "s02.intro2": "Let's set it up.",
        "s02.chooseLanguageSpoken": "Please choose your language.",
        "s02b.title": "Is your school a Tamil Nadu Government school?",
        "s02.schoolCodeSpoken": "Then enter your school code.",
        "s03.title": "What shall I call you?",
        "s03.fieldsSpoken": "Please fill the profile form.",
        "s06.title": "Can we use your camera?",
        "s06.subtitle": "This is completely optional",
        "s06.why1": "Sometimes your face shows how you feel — even when it's hard to say in words",
        "s06.why2": "We never save photos or videos",
        "s06.why3": "We only look at your expressions for a moment",
        "s06.note": "If you say no, ARAM still works fully. Camera is never used without your permission.",
        "s07.title": "Can we listen to your voice?",
        "s07.subtitle": "Also completely optional",
        "s07.why1": "The tone of your voice can tell us how you're really feeling",
        "s07.note": "Voice is separate from camera. You can allow one without the other.",
        "s08.titleSpoken": "You're all set!",
        "s08.readyNote": "ARAM is ready. Let's begin by picking what you'd like to talk about today."
    },
    "hi": {
        "s04.title": "आपके माता-पिता या अभिभावक के लिए एक संदेश",
        "s04.subtitle": "कृपया फ़ोन किसी विश्वसनीय वयस्क को दें",
        "s04.doesTitle": "ARAM क्या करता है",
        "s04.does1": "आपके बच्चे को अपनी भावनाओं के बारे में बात करने में मदद करता है",
        "s04.does2": "संरचित कल्याण जांच प्रदान करता है",
        "s04.does3": "सुरक्षा संबंधी चिंता होने पर हेल्पलाइन से जोड़ता है",
        "s04.privacyTitle": "गोपनीयता वादा",
        "s04.privacy1": "हम आपके बच्चे के जवाब शिक्षकों के साथ साझा नहीं करते",
        "s04.privacy2": "आपातकाल में हेल्पलाइन के साथ केवल न्यूनतम जानकारी साझा की जाती है",
        "s04.privacy3": "आपके बच्चे के सत्र निजी हैं",
        "s04.consentNote": "'मैं अपनी सहमति देता/देती हूँ' पर टैप करके आप पुष्टि करते हैं कि आप एक माता-पिता या अभिभावक हैं और ARAM द्वारा इस बच्चे की सहायता करने से सहमत हैं.",
        "s05.titleSpoken": "क्या मैं यहाँ से आपकी मदद कर सकता हूँ?",
        "s05.canTitle": "मैं यह कर सकता हूँ:",
        "s05.can1": "कठिन भावनाओं को पहचानने और शांत करने में मदद",
        "s05.can2": "छोटे कदम सुझाना जिससे चीजें हल्की लग सकें",
        "s05.can3": "अगर मुझे आपकी सुरक्षा की बहुत चिंता हो, तो असली मददगार तक पहुँचने में मदद",
        "s05.cannotTitle": "मैं यह नहीं कर सकता:",
        "s05.cannot1": "डॉक्टर, शिक्षक, या काउंसलर की जगह लेना",
        "s05.cannot2": "आपके लिए फैसले लेना",
        "s05.cannot3": "आपकी अनुमति के बिना आपकी जानकारी साझा करना, सिवाय आपकी सुरक्षा के लिए",
        "s05.warm": "मैं यहाँ हूँ ताकि आप थोड़ा शांत, थोड़ा स्पष्ट महसूस करें, और अपनी भावनाओं के साथ अकेला न महसूस करें.",
        "s05b.title": "चलिए आपका चेहरा दर्ज करते हैं",
        "s05b.subtitle": "ताकि आप पिन या अपने चेहरे से वापस लॉगिन कर सकें",
        "s05b.captureCtaSpoken": "कृपया दर्ज करें — अपना कैमरा चालू करने के लिए टैप करें.",
        "s11.title": "बस एक बात के बारे में पूछ रहा हूँ",
        "s11.warm": "पिछली बार जब हम बात हुए थे, चीज़ें थोड़ी भारी महसूस हुई थीं. मैं पूछना चाहता था — क्या आप किसी असली व्यक्ति से बात करना चाहेंगे इस बारे में जो आप महसूस कर रहे हैं?",
        "s11.note": "आप जो भी चुनें वह पूरी तरह ठीक है. यह आपकी जगह है.",
        "emergency.title": "अभी आप अकेले नहीं हैं",
        "emergency.subtitle": "अगर आप खतरे में हैं या खुद को नुकसान पहुँचाने के बारे में सोच रहे हैं, तो कृपया संपर्क करें. किसी से बात करना मदद करता है.",
        "emergency.reassure": "संपर्क करना एक साहसी और मजबूत काम है. ये सेवाएं मुफ्त और गोपनीय हैं.",
        "greeting.morning": "शुभ प्रभात",
        "greeting.afternoon": "शुभ दोपहर",
        "greeting.evening": "शुभ संध्या",
        "greeting.night": "शुभ रात्रि",
        "s10.welcomeBackSpoken": "वापसी पर स्वागत है!",
        "s10.proud": "हमें आपकी प्रगति पर गर्व है!",
        "s10.todayLabel": "आज आप क्या करना चाहेंगे?",
        "s01.welcomeSpoken": "आपकी सुरक्षित जगह में आपका स्वागत है. मैं आपकी बात सुनने, साथ देने और बेहतर महसूस कराने के लिए यहाँ हूँ. अपनी यात्रा शुरू करें.",
        "s09.enterPinSpoken": "वापसी पर स्वागत है! अपना पिन दर्ज करें, या अपने पंजीकृत चेहरे से लॉगिन करें.",
        "s09.lockedSub": "आपकी सुरक्षा के लिए यह जगह लॉक कर दी गई है. अनलॉक करने के लिए कृपया अपने स्कूल समन्वयक से संपर्क करें.",
        "s02.intro1": "यह जगह सिर्फ आपके लिए है.",
        "s02.intro2": "चलिए इसे सेट करते हैं.",
        "s02.chooseLanguageSpoken": "कृपया अपनी भाषा चुनें.",
        "s02b.title": "क्या आपका स्कूल तमिलनाडु सरकारी स्कूल है?",
        "s02.schoolCodeSpoken": "फिर अपना स्कूल कोड दर्ज करें.",
        "s03.title": "मैं आपको क्या बुलाऊं?",
        "s03.fieldsSpoken": "कृपया प्रोफ़ाइल फ़ॉर्म भरें.",
        "s06.title": "क्या हम आपके कैमरे का उपयोग कर सकते हैं?",
        "s06.subtitle": "यह पूरी तरह से वैकल्पिक है",
        "s06.why1": "कभी-कभी आपका चेहरा दिखाता है कि आप कैसा महसूस कर रहे हैं — भले ही शब्दों में कहना मुश्किल हो",
        "s06.why2": "हम कभी भी फ़ोटो या वीडियो सेव नहीं करते",
        "s06.why3": "हम केवल एक पल के लिए आपके भावों को देखते हैं",
        "s06.note": "अगर आप ना कहते हैं, तो ARAM फिर भी पूरी तरह काम करेगा. कैमरे का उपयोग आपकी अनुमति के बिना कभी नहीं किया जाता.",
        "s07.title": "क्या हम आपकी आवाज़ सुन सकते हैं?",
        "s07.subtitle": "यह भी पूरी तरह से वैकल्पिक है",
        "s07.why1": "आपकी आवाज़ का लहज़ा बता सकता है कि आप वास्तव में कैसा महसूस कर रहे हैं",
        "s07.note": "आवाज़ कैमरे से अलग है. आप एक की अनुमति दूसरे के बिना दे सकते हैं.",
        "s08.titleSpoken": "आप तैयार हैं!",
        "s08.readyNote": "ARAM तैयार है. चलिए शुरू करते हैं यह चुनकर कि आप आज किस बारे में बात करना चाहते हैं."
    },
    "ta": {
        "s04.title": "உங்கள் பெற்றோர் அல்லது பாதுகாவலருக்கு ஒரு குறிப்பு",
        "s04.subtitle": "தயவுசெய்து தொலைபேசியை நம்பகமான பெரியவரிடம் கொடுக்கவும்",
        "s04.doesTitle": "ARAM என்ன செய்கிறது",
        "s04.does1": "உங்கள் குழந்தை தங்கள் உணர்வுகளைப் பற்றிப் பேச உதவுகிறது",
        "s04.does2": "கட்டமைக்கப்பட்ட நல்வாழ்வு சரிபார்ப்புகளை வழங்குகிறது",
        "s04.does3": "பாதுகாப்பு கவலை இருந்தால் உதவி எண்களுடன் இணைக்கிறது",
        "s04.privacyTitle": "தனியுரிமை உறுதி",
        "s04.privacy1": "உங்கள் குழந்தையின் பதில்களை ஆசிரியர்களுடன் பகிர்வதில்லை",
        "s04.privacy2": "அவசரநிலைகளில் மட்டுமே குறைந்தபட்ச தரவு உதவி எண்களுடன் பகிரப்படும்",
        "s04.privacy3": "உங்கள் குழந்தையின் அமர்வுகள் தனிப்பட்டவை",
        "s04.consentNote": "'நான் என் ஒப்புதலை அளிக்கிறேன்' என்பதைத் தட்டுவதன் மூலம், நீங்கள் பெற்றோர் அல்லது பாதுகாவலர் என்பதை உறுதிப்படுத்தி, இந்தக் குழந்தையை ARAM ஆதரிப்பதை ஏற்கிறீர்கள்.",
        "s05.titleSpoken": "இங்கிருந்து நான் உங்களை ஆதரிக்கலாமா?",
        "s05.canTitle": "நான் செய்யக்கூடியவை:",
        "s05.can1": "கடினமான உணர்வுகளைக் கவனித்து அமைதிப்படுத்த உதவுகிறேன்",
        "s05.can2": "விஷயங்களை இலகுவாக்கக்கூடிய சிறிய படிகளைப் பரிந்துரைக்கிறேன்",
        "s05.can3": "உங்கள் பாதுகாப்பைப் பற்றி நான் மிகவும் கவலைப்பட்டால், உண்மையான உதவியாளரை அடைய உதவுகிறேன்",
        "s05.cannotTitle": "நான் செய்ய முடியாதவை:",
        "s05.cannot1": "மருத்துவர், ஆசிரியர் அல்லது ஆலோசகருக்குப் பதிலாக இருக்க",
        "s05.cannot2": "உங்களுக்காக முடிவுகள் எடுக்க",
        "s05.cannot3": "உங்கள் பாதுகாப்பைத் தவிர, உங்கள் அனுமதியின்றி உங்கள் விவரங்களைப் பகிர",
        "s05.warm": "நீங்கள் சற்று அமைதியாகவும், சற்று தெளிவாகவும், உங்கள் உணர்வுகளுடன் தனியாக இல்லாமலும் உணர உதவ இங்கே இருக்கிறேன்.",
        "s05b.title": "உங்கள் முகத்தைப் பதிவு செய்வோம்",
        "s05b.subtitle": "PIN அல்லது உங்கள் முகத்தைப் பயன்படுத்தி மீண்டும் நுழையலாம்",
        "s05b.captureCtaSpoken": "தயவுசெய்து பதிவு செய்யவும் — உங்கள் கேமராவை இயக்க தட்டவும்.",
        "s11.title": "ஒரு விஷயத்தைப் பற்றி விசாரிக்கிறேன்",
        "s11.warm": "கடந்த முறை நாம் பேசியபோது, விஷயங்கள் சற்று கனமாக இருந்தன. நீங்கள் அனுபவித்தவற்றைப் பற்றி உண்மையான ஒருவரிடம் பேச விரும்புகிறீர்களா என்று கேட்க விரும்பினேன்.",
        "s11.note": "நீங்கள் எதைத் தேர்ந்தெடுத்தாலும் அது முற்றிலும் சரி. இது உங்கள் இடம்.",
        "emergency.title": "இந்த நேரத்தில் நீங்கள் தனியாக இல்லை",
        "emergency.subtitle": "நீங்கள் ஆபத்தில் இருந்தால் அல்லது உங்களைத் தானே காயப்படுத்திக்கொள்ள நினைத்தால், தயவுசெய்து தொடர்பு கொள்ளுங்கள். யாரிடமாவது பேசுவது உதவும்.",
        "emergency.reassure": "தொடர்பு கொள்வது ஒரு தைரியமான, வலிமையான செயல். இந்த சேவைகள் இலவசம் மற்றும் ரகசியமானவை.",
        "greeting.morning": "காலை வணக்கம்",
        "greeting.afternoon": "மதிய வணக்கம்",
        "greeting.evening": "மாலை வணக்கம்",
        "greeting.night": "இனிய இரவு",
        "s10.welcomeBackSpoken": "மீண்டும் வரவேற்கிறோம்!",
        "s10.proud": "உங்கள் முன்னேற்றத்தில் நாங்கள் பெருமிதம் கொள்கிறோம்!",
        "s10.todayLabel": "இன்று நீங்கள் என்ன செய்ய விரும்புகிறீர்கள்?",
        "s01.welcomeSpoken": "உங்கள் பாதுகாப்பான இடத்திற்கு வரவேற்கிறோம். நான் உங்களைக் கேட்கவும், ஆதரிக்கவும், நன்றாக உணர உதவவும் இங்கே இருக்கிறேன். உங்கள் பயணத்தைத் தொடங்குவோம்.",
        "s09.enterPinSpoken": "மீண்டும் வரவேற்கிறோம்! உங்கள் PIN ஐ உள்ளிடவும், அல்லது பதிவு செய்யப்பட்ட உங்கள் முகத்துடன் நுழையவும்.",
        "s09.lockedSub": "உங்கள் பாதுகாப்பிற்காக இந்த இடம் பூட்டப்பட்டுள்ளது. திறக்க உங்கள் பள்ளி ஒருங்கிணைப்பாளரைத் தொடர்பு கொள்ளவும்.",
        "s02.intro1": "இந்த இடம் உங்களுக்காக மட்டுமே.",
        "s02.intro2": "அதை அமைப்போம்.",
        "s02.chooseLanguageSpoken": "தயவுசெய்து உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்.",
        "s02b.title": "உங்கள் பள்ளி தமிழ்நாடு அரசுப் பள்ளியா?",
        "s02.schoolCodeSpoken": "பிறகு உங்கள் பள்ளி குறியீட்டை உள்ளிடவும்.",
        "s03.title": "உங்களை என்ன அழைக்கட்டும்?",
        "s03.fieldsSpoken": "தயவுசெய்து சுயவிவரப் படிவத்தை நிரப்பவும்.",
        "s06.title": "உங்கள் கேமராவைப் பயன்படுத்தலாமா?",
        "s06.subtitle": "இது முற்றிலும் விருப்பமானது",
        "s06.why1": "சில நேரங்களில் வார்த்தைகளில் சொல்வது கடினமாக இருந்தாலும், உங்கள் முகம் உங்கள் உணர்வைக் காட்டுகிறது",
        "s06.why2": "நாங்கள் புகைப்படங்கள் அல்லது வீடியோக்களை ஒருபோதும் சேமிப்பதில்லை",
        "s06.why3": "உங்கள் முகபாவனைகளை ஒரு கணம் மட்டுமே பார்க்கிறோம்",
        "s06.note": "நீங்கள் வேண்டாம் என்றால், ARAM முழுமையாக இயங்கும். உங்கள் அனுமதியின்றி கேமரா ஒருபோதும் பயன்படுத்தப்படாது.",
        "s07.title": "உங்கள் குரலைக் கேட்கலாமா?",
        "s07.subtitle": "இதுவும் முற்றிலும் விருப்பமானது",
        "s07.why1": "உங்கள் குரலின் தொனி நீங்கள் உண்மையில் எப்படி உணர்கிறீர்கள் என்பதைச் சொல்லும்",
        "s07.note": "குரல் கேமராவிலிருந்து தனியானது. ஒன்றை மற்றொன்று இல்லாமல் அனுமதிக்கலாம்.",
        "s08.titleSpoken": "நீங்கள் தயார்!",
        "s08.readyNote": "ARAM தயார். இன்று நீங்கள் எதைப் பற்றிப் பேச விரும்புகிறீர்கள் என்பதைத் தேர்ந்தெடுப்பதன் மூலம் தொடங்குவோம்."
    },
    "te": {
        "s04.title": "మీ తల్లిదండ్రులు లేదా సంరక్షకుని కోసం ఒక గమనిక",
        "s04.subtitle": "దయచేసి ఫోన్‌ను నమ్మకమైన పెద్దవారికి ఇవ్వండి",
        "s04.doesTitle": "ARAM ఏమి చేస్తుంది",
        "s04.does1": "మీ పిల్లవాడు తమ భావాల గురించి మాట్లాడటానికి సహాయపడుతుంది",
        "s04.does2": "నిర్మాణాత్మక శ్రేయస్సు తనిఖీలను అందిస్తుంది",
        "s04.does3": "భద్రతా ఆందోళన ఉంటే హెల్ప్‌లైన్‌లకు కనెక్ట్ చేస్తుంది",
        "s04.privacyTitle": "గోప్యతా వాగ్దానం",
        "s04.privacy1": "మేము మీ పిల్లవాడి సమాధానాలను ఉపాధ్యాయులతో పంచుకోము",
        "s04.privacy2": "అత్యవసర పరిస్థితుల్లో హెల్ప్‌లైన్‌లతో కనీస డేటా మాత్రమే పంచుకోబడుతుంది",
        "s04.privacy3": "మీ పిల్లవాడి సెషన్‌లు ప్రైవేట్",
        "s04.consentNote": "'నేను నా సమ్మతిని ఇస్తున్నాను' అని నొక్కడం ద్వారా మీరు తల్లిదండ్రి లేదా సంరక్షకులని నిర్ధారిస్తారు మరియు ARAM ఈ పిల్లవాడికి మద్దతు ఇవ్వడానికి అంగీకరిస్తారు.",
        "s05.titleSpoken": "నేను ఇక్కడి నుండి మీకు మద్దతు ఇవ్వవచ్చా?",
        "s05.canTitle": "నేను చేయగలిగినవి:",
        "s05.can1": "కష్టమైన భావాలను గమనించి శాంతపరచడంలో సహాయం",
        "s05.can2": "విషయాలను తేలికగా చేయగల చిన్న అడుగులను సూచించడం",
        "s05.can3": "మీ భద్రత గురించి నేను చాలా ఆందోళన చెందితే, నిజమైన సహాయకుడిని చేరుకోవడంలో సహాయం",
        "s05.cannotTitle": "నేను చేయలేనివి:",
        "s05.cannot1": "డాక్టర్, ఉపాధ్యాయుడు లేదా కౌన్సెలర్ స్థానంలో ఉండటం",
        "s05.cannot2": "మీ కోసం నిర్ణయాలు తీసుకోవడం",
        "s05.cannot3": "మీ భద్రత కోసం తప్ప, మీ అనుమతి లేకుండా మీ వివరాలను పంచుకోవడం",
        "s05.warm": "మీరు కొంచెం ప్రశాంతంగా, కొంచెం స్పష్టంగా, మీ భావాలతో ఒంటరిగా కాకుండా అనుభూతి చెందడానికి నేను సహాయం చేయడానికి ఇక్కడ ఉన్నాను.",
        "s05b.title": "మీ ముఖాన్ని నమోదు చేద్దాం",
        "s05b.subtitle": "తద్వారా మీరు పిన్ లేదా మీ ముఖంతో తిరిగి లాగిన్ కావచ్చు",
        "s05b.captureCtaSpoken": "దయచేసి నమోదు చేయండి — మీ కెమెరాను ఆన్ చేయడానికి నొక్కండి.",
        "s11.title": "ఒక విషయం గురించి అడుగుతున్నాను",
        "s11.warm": "మనం చివరిసారి మాట్లాడినప్పుడు, విషయాలు కొంచెం భారంగా అనిపించాయి. మీరు అనుభవించిన దాని గురించి నిజమైన వ్యక్తితో మాట్లాడాలనుకుంటున్నారా అని నేను అడగాలనుకున్నాను?",
        "s11.note": "మీరు ఏది ఎంచుకున్నా అది పూర్తిగా సరే. ఇది మీ స్థలం.",
        "emergency.title": "ఇప్పుడు మీరు ఒంటరిగా లేరు",
        "emergency.subtitle": "మీరు ప్రమాదంలో ఉంటే లేదా మిమ్మల్ని మీరు గాయపరచుకోవాలని ఆలోచిస్తుంటే, దయచేసి సంప్రదించండి. ఎవరితోనైనా మాట్లాడటం సహాయపడుతుంది.",
        "emergency.reassure": "సంప్రదించడం ధైర్యమైన మరియు బలమైన పని. ఈ సేవలు ఉచితం మరియు గోప్యమైనవి.",
        "greeting.morning": "శుభోదయం",
        "greeting.afternoon": "శుభ మధ్యాహ్నం",
        "greeting.evening": "శుభ సాయంత్రం",
        "greeting.night": "శుభరాత్రి",
        "s10.welcomeBackSpoken": "తిరిగి స్వాగతం!",
        "s10.proud": "మీ పురోగతి గురించి మేము గర్విస్తున్నాము!",
        "s10.todayLabel": "ఈ రోజు మీరు ఏమి చేయాలనుకుంటున్నారు?",
        "s01.welcomeSpoken": "మీ సురక్షిత స్థలానికి స్వాగతం. మిమ్మల్ని వినడానికి, మద్దతు ఇవ్వడానికి, మంచి అనుభూతి కలిగించడానికి నేను ఇక్కడ ఉన్నాను. మీ ప్రయాణాన్ని ప్రారంభించండి.",
        "s09.enterPinSpoken": "తిరిగి స్వాగతం! మీ పిన్‌ని నమోదు చేయండి, లేదా నమోదు చేసిన మీ ముఖంతో లాగిన్ చేయండి.",
        "s09.lockedSub": "మీ భద్రత కోసం ఈ స్థలం లాక్ చేయబడింది. అన్‌లాక్ చేయడానికి దయచేసి మీ పాఠశాల సమన్వయకర్తను సంప్రదించండి.",
        "s02.intro1": "ఈ స్థలం మీ కోసమే.",
        "s02.intro2": "దీన్ని సెటప్ చేద్దాం.",
        "s02.chooseLanguageSpoken": "దయచేసి మీ భాషను ఎంచుకోండి.",
        "s02b.title": "మీ పాఠశాల తమిళనాడు ప్రభుత్వ పాఠశాలనా?",
        "s02.schoolCodeSpoken": "తర్వాత మీ పాఠశాల కోడ్‌ని నమోదు చేయండి.",
        "s03.title": "మిమ్మల్ని ఏమని పిలవాలి?",
        "s03.fieldsSpoken": "దయచేసి ప్రొఫైల్ ఫారమ్‌ను పూరించండి.",
        "s06.title": "మేము మీ కెమెరాను ఉపయోగించవచ్చా?",
        "s06.subtitle": "ఇది పూర్తిగా ఐచ్ఛికం",
        "s06.why1": "కొన్నిసార్లు మీ ముఖం మీరు ఎలా భావిస్తున్నారో చూపిస్తుంది — మాటల్లో చెప్పడం కష్టమైనా",
        "s06.why2": "మేము ఎప్పుడూ ఫోటోలు లేదా వీడియోలను సేవ్ చేయము",
        "s06.why3": "మేము మీ హావభావాలను ఒక క్షణం మాత్రమే చూస్తాము",
        "s06.note": "మీరు వద్దు అంటే, ARAM ఇప్పటికీ పూర్తిగా పనిచేస్తుంది. మీ అనుమతి లేకుండా కెమెరా ఎప్పుడూ ఉపయోగించబడదు.",
        "s07.title": "మేము మీ స్వరం వినవచ్చా?",
        "s07.subtitle": "ఇది కూడా పూర్తిగా ఐచ్ఛికం",
        "s07.why1": "మీ స్వరం యొక్క టోన్ మీరు నిజంగా ఎలా భావిస్తున్నారో చెప్పగలదు",
        "s07.note": "స్వరం కెమెరా నుండి వేరు. మీరు ఒకదానికి మరొకటి లేకుండా అనుమతించవచ్చు.",
        "s08.titleSpoken": "మీరు సిద్ధంగా ఉన్నారు!",
        "s08.readyNote": "ARAM సిద్ధంగా ఉంది. ఈ రోజు మీరు దేని గురించి మాట్లాడాలనుకుంటున్నారో ఎంచుకోవడం ద్వారా ప్రారంభిద్దాం."
    },
    "ml": {
        "s04.title": "നിങ്ങളുടെ മാതാപിതാക്കൾക്കോ രക്ഷിതാവിനോ ഒരു കുറിപ്പ്",
        "s04.subtitle": "ദയവായി ഫോൺ വിശ്വസ്തനായ ഒരു മുതിർന്ന ആൾക്ക് കൈമാറുക",
        "s04.doesTitle": "ARAM എന്ത് ചെയ്യുന്നു",
        "s04.does1": "നിങ്ങളുടെ കുട്ടിയെ അവരുടെ വികാരങ്ങളെക്കുറിച്ച് സംസാരിക്കാൻ സഹായിക്കുന്നു",
        "s04.does2": "ക്രമീകൃതമായ ക്ഷേമ പരിശോധനകൾ നൽകുന്നു",
        "s04.does3": "സുരക്ഷാ ആശങ്കയുണ്ടെങ്കിൽ ഹെൽപ്‌ലൈനുകളുമായി ബന്ധിപ്പിക്കുന്നു",
        "s04.privacyTitle": "സ്വകാര്യതാ വാഗ്ദാനം",
        "s04.privacy1": "ഞങ്ങൾ നിങ്ങളുടെ കുട്ടിയുടെ പ്രതികരണങ്ങൾ അധ്യാപകരുമായി പങ്കിടില്ല",
        "s04.privacy2": "അടിയന്തര സാഹചര്യങ്ങളിൽ ഹെൽപ്‌ലൈനുകളുമായി ഏറ്റവും കുറഞ്ഞ വിവരങ്ങൾ മാത്രം പങ്കിടും",
        "s04.privacy3": "നിങ്ങളുടെ കുട്ടിയുടെ സെഷനുകൾ സ്വകാര്യമാണ്",
        "s04.consentNote": "'ഞാൻ എന്റെ സമ്മതം നൽകുന്നു' എന്നതിൽ ടാപ്പ് ചെയ്യുന്നതിലൂടെ നിങ്ങൾ ഒരു മാതാപിതാവോ രക്ഷിതാവോ ആണെന്ന് സ്ഥിരീകരിക്കുകയും ARAM ഈ കുട്ടിയെ പിന്തുണയ്ക്കുന്നതിന് സമ്മതിക്കുകയും ചെയ്യുന്നു.",
        "s05.titleSpoken": "ഇവിടെ നിന്ന് എനിക്ക് നിങ്ങളെ പിന്തുണയ്ക്കാമോ?",
        "s05.canTitle": "എനിക്ക് ചെയ്യാൻ കഴിയുന്നത്:",
        "s05.can1": "ബുദ്ധിമുട്ടുള്ള വികാരങ്ങൾ ശ്രദ്ധിക്കാനും ശാന്തമാക്കാനും സഹായിക്കുക",
        "s05.can2": "കാര്യങ്ങൾ ലഘുവാക്കാൻ കഴിയുന്ന ചെറിയ നടപടികൾ നിർദ്ദേശിക്കുക",
        "s05.can3": "നിങ്ങളുടെ സുരക്ഷയെക്കുറിച്ച് ഞാൻ വളരെ ആശങ്കാകുലനാണെങ്കിൽ, ഒരു യഥാർത്ഥ സഹായിയെ ബന്ധപ്പെടാൻ സഹായിക്കുക",
        "s05.cannotTitle": "എനിക്ക് ചെയ്യാൻ കഴിയാത്തത്:",
        "s05.cannot1": "ഒരു ഡോക്ടറുടെയോ അധ്യാപകന്റെയോ കൗൺസിലറുടെയോ സ്ഥാനത്ത് നിൽക്കുക",
        "s05.cannot2": "നിങ്ങൾക്ക് വേണ്ടി തീരുമാനങ്ങൾ എടുക്കുക",
        "s05.cannot3": "നിങ്ങളുടെ സുരക്ഷയ്ക്ക് വേണ്ടിയല്ലാതെ, നിങ്ങളുടെ അനുവാദമില്ലാതെ നിങ്ങളുടെ വിവരങ്ങൾ പങ്കിടുക",
        "s05.warm": "നിങ്ങൾക്ക് അൽപ്പം ശാന്തതയും വ്യക്തതയും തോന്നാനും, നിങ്ങളുടെ വികാരങ്ങളുമായി തനിച്ചല്ലെന്ന് തോന്നാനും സഹായിക്കാൻ ഞാൻ ഇവിടെയുണ്ട്.",
        "s05b.title": "നമുക്ക് നിങ്ങളുടെ മുഖം രജിസ്റ്റർ ചെയ്യാം",
        "s05b.subtitle": "അതിനാൽ നിങ്ങൾക്ക് പിൻ ഉപയോഗിച്ചോ മുഖം ഉപയോഗിച്ചോ തിരികെ ലോഗിൻ ചെയ്യാം",
        "s05b.captureCtaSpoken": "ദയവായി രജിസ്റ്റർ ചെയ്യുക — നിങ്ങളുടെ ക്യാമറ ഓണാക്കാൻ ടാപ്പ് ചെയ്യുക.",
        "s11.title": "ഒരു കാര്യത്തെക്കുറിച്ച് ചോദിക്കുന്നു",
        "s11.warm": "കഴിഞ്ഞ തവണ നാം സംസാരിച്ചപ്പോൾ, കാര്യങ്ങൾ അൽപ്പം ഭാരമായി തോന്നി. നിങ്ങൾ കടന്നുപോയതിനെക്കുറിച്ച് ഒരു യഥാർത്ഥ വ്യക്തിയോട് സംസാരിക്കാൻ ആഗ്രഹിക്കുന്നുണ്ടോ എന്ന് ഞാൻ ചോദിക്കാൻ ആഗ്രഹിച്ചു.",
        "s11.note": "നിങ്ങൾ എന്ത് തിരഞ്ഞെടുത്താലും അത് പൂർണ്ണമായും ശരിയാണ്. ഇത് നിങ്ങളുടെ ഇടമാണ്.",
        "emergency.title": "ഇപ്പോൾ നിങ്ങൾ തനിച്ചല്ല",
        "emergency.subtitle": "നിങ്ങൾ അപകടത്തിലാണെങ്കിൽ അല്ലെങ്കിൽ സ്വയം ഉപദ്രവിക്കാൻ ചിന്തിക്കുന്നുവെങ്കിൽ, ദയവായി ബന്ധപ്പെടുക. ആരോടെങ്കിലും സംസാരിക്കുന്നത് സഹായിക്കും.",
        "emergency.reassure": "ബന്ധപ്പെടുന്നത് ധൈര്യവും ശക്തിയുമുള്ള ഒരു കാര്യമാണ്. ഈ സേവനങ്ങൾ സൗജന്യവും രഹസ്യാത്മകവുമാണ്.",
        "greeting.morning": "സുപ്രഭാതം",
        "greeting.afternoon": "ശുഭ മധ്യാഹ്നം",
        "greeting.evening": "ശുഭ സായാഹ്നം",
        "greeting.night": "ശുഭരാത്രി",
        "s10.welcomeBackSpoken": "തിരികെ സ്വാഗതം!",
        "s10.proud": "നിങ്ങളുടെ പുരോഗതിയിൽ ഞങ്ങൾ അഭിമാനിക്കുന്നു!",
        "s10.todayLabel": "ഇന്ന് നിങ്ങൾ എന്ത് ചെയ്യാൻ ആഗ്രഹിക്കുന്നു?",
        "s01.welcomeSpoken": "നിങ്ങളുടെ സുരക്ഷിത ഇടത്തിലേക്ക് സ്വാഗതം. നിങ്ങളെ കേൾക്കാനും, പിന്തുണയ്ക്കാനും, കൂടുതൽ നല്ലത് അനുഭവിക്കാൻ സഹായിക്കാനും ഞാൻ ഇവിടെയുണ്ട്. നിങ്ങളുടെ യാത്ര ആരംഭിക്കാം.",
        "s09.enterPinSpoken": "തിരികെ സ്വാഗതം! നിങ്ങളുടെ പിൻ നൽകുക, അല്ലെങ്കിൽ രജിസ്റ്റർ ചെയ്ത നിങ്ങളുടെ മുഖം ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക.",
        "s09.lockedSub": "നിങ്ങളുടെ സുരക്ഷയ്ക്കായി ഈ ഇടം ലോക്ക് ചെയ്തിരിക്കുന്നു. അൺലോക്ക് ചെയ്യാൻ ദയവായി നിങ്ങളുടെ സ്കൂൾ കോർഡിനേറ്ററെ ബന്ധപ്പെടുക.",
        "s02.intro1": "ഈ ഇടം നിങ്ങൾക്ക് വേണ്ടി മാത്രമാണ്.",
        "s02.intro2": "നമുക്ക് ഇത് സജ്ജമാക്കാം.",
        "s02.chooseLanguageSpoken": "ദയവായി നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക.",
        "s02b.title": "നിങ്ങളുടെ സ്കൂൾ തമിഴ്‌നാട് സർക്കാർ സ്കൂളാണോ?",
        "s02.schoolCodeSpoken": "പിന്നെ നിങ്ങളുടെ സ്കൂൾ കോഡ് നൽകുക.",
        "s03.title": "നിങ്ങളെ എന്ത് വിളിക്കണം?",
        "s03.fieldsSpoken": "ദയവായി പ്രൊഫൈൽ ഫോം പൂരിപ്പിക്കുക.",
        "s06.title": "ഞങ്ങൾക്ക് നിങ്ങളുടെ ക്യാമറ ഉപയോഗിക്കാമോ?",
        "s06.subtitle": "ഇത് പൂർണ്ണമായും ഐച്ഛികമാണ്",
        "s06.why1": "ചിലപ്പോൾ വാക്കുകളിൽ പറയാൻ പ്രയാസമാണെങ്കിലും, നിങ്ങളുടെ മുഖം നിങ്ങൾക്ക് എങ്ങനെ തോന്നുന്നു എന്ന് കാണിക്കും",
        "s06.why2": "ഞങ്ങൾ ഒരിക്കലും ഫോട്ടോകളോ വീഡിയോകളോ സൂക്ഷിക്കില്ല",
        "s06.why3": "ഞങ്ങൾ ഒരു നിമിഷം മാത്രം നിങ്ങളുടെ ഭാവങ്ങൾ നോക്കുന്നു",
        "s06.note": "നിങ്ങൾ വേണ്ട എന്ന് പറഞ്ഞാൽ, ARAM ഇപ്പോഴും പൂർണ്ണമായി പ്രവർത്തിക്കും. നിങ്ങളുടെ അനുവാദമില്ലാതെ ക്യാമറ ഒരിക്കലും ഉപയോഗിക്കില്ല.",
        "s07.title": "ഞങ്ങൾക്ക് നിങ്ങളുടെ ശബ്ദം കേൾക്കാമോ?",
        "s07.subtitle": "ഇതും പൂർണ്ണമായും ഐച്ഛികമാണ്",
        "s07.why1": "നിങ്ങളുടെ ശബ്ദത്തിന്റെ ടോൺ നിങ്ങൾക്ക് യഥാർത്ഥത്തിൽ എങ്ങനെ തോന്നുന്നു എന്ന് പറയാൻ കഴിയും",
        "s07.note": "ശബ്ദം ക്യാമറയിൽ നിന്ന് വ്യത്യസ്തമാണ്. നിങ്ങൾക്ക് ഒന്ന് മറ്റേതില്ലാതെ അനുവദിക്കാം.",
        "s08.titleSpoken": "നിങ്ങൾ തയ്യാറാണ്!",
        "s08.readyNote": "ARAM തയ്യാറാണ്. ഇന്ന് നിങ്ങൾ എന്തിനെക്കുറിച്ച് സംസാരിക്കണമെന്ന് തിരഞ്ഞെടുത്ത് നമുക്ക് തുടങ്ങാം."
    }
}


def main() -> None:
    import soundfile as sf
    import torch
    from parler_tts import ParlerTTSForConditionalGeneration
    from transformers import AutoTokenizer

    if not shutil.which("ffmpeg"):
        sys.exit("error: ffmpeg not found")

    device = "cuda:0" if torch.cuda.is_available() else "cpu"
    if device == "cpu":
        print("device: CPU — no GPU found. Expect hours, not minutes.")
        print("Colab: Runtime > Change runtime type > T4 GPU, then rerun.")
    else:
        print(f"device: {device} ({torch.cuda.get_device_name(0)})")

    print(f"loading {MODEL_ID} …")
    model = ParlerTTSForConditionalGeneration.from_pretrained(MODEL_ID).to(device)
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    desc_tokenizer = AutoTokenizer.from_pretrained(model.config.text_encoder._name_or_path)
    rate = model.config.sampling_rate

    for lang, entries in TEXTS.items():
        out_dir = OUT / lang
        out_dir.mkdir(parents=True, exist_ok=True)
        tmp = out_dir / "_tmp.wav"
        desc = DESCRIPTIONS[lang]
        print(f"\n[{lang}] voice: {desc}")

        desc_ids = desc_tokenizer(desc, return_tensors="pt").to(device)
        for i, (key, text) in enumerate(entries.items(), 1):
            mp3 = out_dir / f"{key}.mp3"
            if mp3.exists():
                print(f"[{lang}] {i}/{len(entries)} {key} — exists, skipping")
                continue
            print(f"[{lang}] {i}/{len(entries)} {key}: {text[:60]}…")
            # Per-clip seed: one bad line can be deleted and re-rendered without
            # disturbing the others that were already listened to and approved.
            torch.manual_seed(SEED)
            prompt_ids = tokenizer(text, return_tensors="pt").to(device)
            generation = model.generate(
                input_ids=desc_ids.input_ids,
                attention_mask=desc_ids.attention_mask,
                prompt_input_ids=prompt_ids.input_ids,
                prompt_attention_mask=prompt_ids.attention_mask,
            )
            sf.write(tmp, generation.cpu().numpy().squeeze(), samplerate=rate)
            subprocess.run(
                ["ffmpeg", "-y", "-loglevel", "error", "-i", str(tmp), "-af", AUDIO_FILTER,
                 "-codec:a", "libmp3lame", "-b:a", MP3_BITRATE, "-ac", "1",
                 "-ar", str(rate), str(mp3)],
                check=True,
            )
        tmp.unlink(missing_ok=True)

    shutil.make_archive("aram-audio", "zip", OUT)
    clips = list(OUT.rglob("*.mp3"))
    size = sum(f.stat().st_size for f in clips) / 1_048_576
    print(f"\ndone — {len(clips)} clips, {size:.2f} MB -> aram-audio.zip")
    print("Unzip into public/audio/ so you get public/audio/en/*.mp3 and .../ta/*.mp3")


if __name__ == "__main__":
    main()
